DBG_DIR=/usr/lib/debug
INSTALL_DIR=/usr/local/bin

all:

install:
	./install.sh
	./sting_gen_interpreter_info bash
	./sting_gen_interpreter_info php5

clean:

uninstall:
	rm -f /etc/sting/interpreter_info 
