# TODO: CONFIG_STING
obj-y	+=	dict.o
obj-y	+=	ept_dict.o
obj-y	+=	sting.o
obj-y	+=	syscall_filename.o
obj-y	+=	permission.o
obj-y	+=	launch_attack.o
ccflags-y := -Ikernel/sting/include

# CFLAGS_ept_dict.o	:=	-O0
