#!/usr/bin/env python
import xattr
import os
import sys

ATTACKER_MARKED_XATTR = "security.attacker"

if len(sys.argv) < 2:
	sys.exit(1)

xattrl = xattr.list(sys.argv[1], nofollow=True)

if ATTACKER_MARKED_XATTR in xattrl:
	print "%s: STING marked" % (sys.argv[1])
else:
	print "%s: not STING marked" % (sys.argv[1])
