#! /bin/sh -e

PREREQ=""

prereqs () {
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

# Console utilities needed for console-setup
copy_exec /usr/local/bin/sting_restore_ept_dict /bin

exit 0
